### ISSUE TITLE
No more documentation on www.ied3vil.com

### ISSUE THREAD

**Issue by jardasmahel** [ied3vil/LanguageSwitcher#17] opened 2019-01-25 07:33 UTC
Your website www.ied3vil.com has been taken over by some Chinese guys.

**Comment by ied3vil** [comment] 2019-01-27 17:44
I have not renewed it, that is the cause... closing the issue, thanks for letting me know! i will update the readme to stop pointing to it

**Closed as completed by ied3vil** 2019-01-27 17:44 UTC
